Repository Techtonica/keyboard-shortcuts-practice, pull requests merged in 2020-10, with the labels that each got.

#91 Resolves #65 - Finish ORM Setup
  .env.example
  .gitignore
  JS/config.js
  JS/orm.js
  app.js
  package-lock.json
  package.json
Labels: GraceHopperOSD

#107 Remove unneeded files
  shortcuts.txt
  userinfo.html
Labels: GraceHopperOSD, Hacktoberfest

#109 Remove jQuery when possible
  package.json
  public/scripts/main.js
Labels: needs reviewer

#116 Fixes #67: Save answer POST request
  JS/router.js
  public/scripts/main.js
  routes/routes.js
Labels: waiting-on-pr-revision

#103 added shortcut type tag to JSON object and main screen
  public/CSS/main.css
  public/scripts/main.js
  public/scripts/shortcuts.json
  views/index.ejs
Labels: needs reviewer

#115 Replaced jQuery DOM Selectors with in-built one
  public/scripts/main.js
Labels: waiting-on-pr-revision

#119 Fixes #73 Integrate Auth0 middleware into the server
  .env.example
  JS/auth0.js
  README.md
  app.js
  package-lock.json
  package.json
Labels: needs reviewer

#124 Replace Window Resizing Listener
  public/CSS/main.css
  public/scripts/main.js
Labels: needs reviewer

#125 Fixes #104 Replace jQuery.text function
  public/scripts/main.js
Labels: needs reviewer

#127 feat: add toggle to show/hide button hint
  public/CSS/main.css
  public/scripts/main.js
  views/index.ejs
Labels: needs reviewer

#126 Updated ecstatic to v 4.1.4
  package-lock.json
  package.json
Labels: needs reviewer

#134 split list keyboard into lists per row
  public/CSS/main.css
  views/index.ejs
Labels: hacktoberfest-accepted

#118 most command hotkeys escaped instead of executed #45
  package-lock.json
  package.json
  public/scripts/main.js
Labels: hacktoberfest-accepted

#137 Add highlight for Fn key in case F1-F12 is pressed. Fixes #29
  public/scripts/main.js
  public/scripts/shortcuts.json
Labels: hacktoberfest-accepted

#132 Fix #96: Add ability to retrieve timing history
  public/scripts/history.js
  public/scripts/main.js
  routes/routes.js
Labels: waiting-on-pr-revision

#135 Fix: #99 Change jquery CSS functions in main.js
  public/scripts/main.js
  views/index.ejs
Labels: waiting-on-pr-revision

#140 Added favicon
  app.js
  package-lock.json
  package.json
  public/images/favicon.ico
Labels: hacktoberfest-accepted

#133 App can use Auth0 or local dev auth
  .env.example
  .gitignore
  JS/auth-dev.js
  JS/auth-setup.js
  JS/auth0.js
  JS/config.js
  JS/orm.js
  JS/router.js
  app.js
  package-lock.json
  package.json
  routes/routes.js
  views/index.ejs
Labels: authentication, needs reviewer
